### ISSUE TITLE
useQuery alternative to graphql() + query

### ISSUE THREAD

**Issue by natew** [samdenty/gqless#107] opened 2020-05-08 23:40 UTC
This would be to remove the need to wrap components with `graphql`.

Basically useQuery returns the same proxy that tracks things just like usual, but then uses the same hack overmind and others use to detect "end of render", and since it's a hook can just re-render the component.

This would have the added advantage of also allowing hooks to be used and composed more easily, you can create any hook and use it anywhere without worrying about wrapping issues.

**Comment by natew** [comment] 2020-05-11 19:42
Looks like this has already been created actually, 3d party: https://github.com/dai-shi/gqless-hook

**Comment by samdenty** [comment] 2020-05-20 21:13
duplicate of https://github.com/samdenty/gqless/issues/58

**Closed by samdenty** 2020-05-20 21:13 UTC
Labels: duplicate
